### ISSUE TITLE
Fetchutil.orgfetch local doesn't work

### ISSUE THREAD

**Issue by solarknow** [solarknow/pevolution#1]
Traceback (most recent call last):
  File "initblast.py", line 19, in <module>
    dom=Fetchutil.orgfetch(query,local)
  File "/home/sarwamih/pevolution/Fetchutil.py", line 68, in orgfetch
    taxid=dict_all[acc]
KeyError: '28188321'

**Comment by solarknow** [comment]
Architecture has changed significantly since. reopen if problem persists.
